### ISSUE TITLE
Naming Conventions: Folder vs Directory 

### ISSUE THREAD

**Issue by patkearns10** [dbt-labs/dbt-project-evaluator#123]
### Describe the bug

I noticed we use subfolder and subdirectory rather interchangeably. Should we standardize on one? If so, which?

#### internet says:
> If one is referring to a container of documents, the term folder is more appropriate. The term directory refers to the way a structured list of document files and folders is stored on the computer. It is comparable to a telephone directory that contains lists of names, numbers and addresses and does not contain the actual documents themselves.
[source](https://stackoverflow.com/questions/5078676/what-is-the-difference-between-a-directory-and-a-folder#:~:text=between%20individual%20installations.-,If%20one%20is%20referring%20to%20a%20container%20of%20documents%2C%20the%20term,numbers%20and%20addresses%20and%20does%20not%20contain%20the%20actual%20documents%20themselves.,-Share)

#### current counts in readme:
folder = 24
subfolder = 2

directory = 58
subdirectory = 34

#### We have fields named:
- directory
  - directory_path
  - child_directory_path
  - parent_directory_path
  - test_yml_directory_path
  - model_directory_path
  - current_test_directory
  - change_test_directory_to
- path
  - file_path
  - current_file_path
  - change_file_path_to
  - parent_file_path
  - child_file_path

#### We have variables named:
- staging_folder_name
- intermediate_folder_name
- marts_folder_name

#### We have models named:
- stg_naming_convention_folders
- fct_model_directories
- fct_source_directories
- fct_test_directories

### Expected results

Stick to one or the other, or be conscious of the decision if we do use both

**Comment by dave-connors-3** [comment]
@patkearns10 you want to do this one?
