### ISSUE TITLE
Databricks support

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#133]
### Describe the feature
Allow databricks users to run the package

### Additional context
[Community has requested this functionality!](https://getdbt.slack.com/archives/C01NH3F2E05/p1655139152074579?thread_ts=1655126255.889019&cid=C01NH3F2E05)

### Who will this benefit?
Databricks users

**Comment by b-per** [comment]
#134 is adding support for databricks/spark
