### ISSUE TITLE
Metrics lineage is not reported

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-project-evaluator#139]
Any reason why we are joining the exposures parents but not the metrics in the code below?

It looks like something I missed (the CTE `direct_metrics_relationships` is created but not used) but I wanted to confirm that this is not something we implemented like this by design.

https://github.com/dbt-labs/dbt-project-evaluator/blob/12b1c2cc531e7ffe48f8040dbed1ad25374fa5a7/models/marts/core/int_direct_relationships.sql#L17-L52

**Comment by graciegoheen** [comment]
This looks like a bug to me - I don't think this was done intentionally. @dave-connors-3 can you confirm?
