### ISSUE TITLE
Move arrays macros for Databricks/Spark from this repo to `spark_utils`

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-project-evaluator#154]
Currently, a Databricks user needs to configure the `search_order` for the package `dbt_utils` to be reading from `dbt_project_evaulator` first due to the fact that we use array macros that are not in `spark_utils` yet.

We should make sure that those macros work in all cases (not just the cases of this package) and move them to `spark_utils`.

**Comment by graciegoheen** [comment]
Got the ball rolling for array macros (will do a separate PR for listagg) - https://github.com/dbt-labs/spark-utils/pull/26
