### ISSUE TITLE
Compilation error in model stg_nodes

### ISSUE THREAD

**Issue by pkanter** [dbt-labs/dbt-project-evaluator#163]
### Describe the bug
When trying to compile the package, error prevents successful compilation.

### Steps to reproduce
Executed the following: dbt run --select dbt_project_evaluator

### Screenshots and log output
15:57:07  Database Error in model stg_nodes (models\staging\graph\stg_nodes.sql)
15:57:07    001831 (42601): SQL compilation error: error line 2,074 at position 14
15:57:07    Invalid unicode escape sequence '\u'; should be exactly 4 digits.
15:57:07    compiled SQL at target\run\dbt_project_evaluator\models\staging\graph\stg_nodes.sql

### System information
packages:
  - package: calogica/dbt_date
    version: [">=0.5.0", "<0.6.0"]
    
  - package: dbt-labs/audit_helper
    version: 0.5.0

  - package: fivetran/fivetran_log
    version: 0.6.1

  - package: dbt-labs/codegen
    version: 0.7.0

  - package: fivetran/shopify_source
    version: [">=0.6.0", "<0.7.0"]
    
  - package: fivetran/shopify
    version: [">=0.6.0", "<0.7.0"]

  - package: dbt-labs/dbt_project_evaluator
    version: 0.1.1

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.0
  - latest:    1.1.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.1.0 - Up to date!
```

**Comment by pkanter** [comment]
@b-per , sorry for the delay in getting back to you.  I'll get the file you requested and will send to you via Slack DM.

**Comment by b-per** [comment]
Thanks @pkanter !

The issue is that there is a folder starting with `u` and on Windows, path parts are split with `\` (instead of `/` on Mac and Linux), which results to `\u` which is the prefix for a unicode number in Snowflake.

I will fix it shortly.
