### ISSUE TITLE
Add meta in stg_nodes

### ISSUE THREAD

**Issue by chaos87** [dbt-labs/dbt-project-evaluator#164]
Hi there 👋 ,

Thanks for this repo!
I am very interested in leveraging the models you've built to have the foundation for a data catalog at my company.

We heavily use `meta` on sources, models and exposures and it would be neat to have this field populated in stg_nodes and the downstream views

**Comment by b-per** [comment]
Hi!

Would you be able to describe a bit more how you are using the meta field and how you would like to query it?
`meta` being a dictionary, would it work with you if it was added as a JSON string for each model?

**Comment by chaos87** [comment]
Hi!

For models/sources: we are storing `owner` (for nodes other than exposures) in meta field. 
For exposures: we store `stakeholders` to know which team or squad depends on an exposure

I'm totally fine with it being a JSON string. I use BigQuery and it's supported.

Thanks!

**Comment by b-per** [comment]
This has been added to the project.
