### ISSUE TITLE
Add description in stg_nodes and views

### ISSUE THREAD

**Issue by chaos87** [dbt-labs/dbt-project-evaluator#168]
Hi!

I would like to be able to extract the `description` field for models, sources, metrics and exposures.

Let me know if you need more info on how I intend to use it

(Really appreciate the prompt reaction each time! 🙌)

**Comment by b-per** [comment]
Hi! Thanks for raising the issue. And, yes, could you please explain what you would do with those descriptions?

We used to extract all the descriptions at the beginning of the project but got [some errors](https://github.com/dbt-labs/dbt-project-evaluator/issues/9) related to the fact that the query to load the models was then too big and wouldn't run. So, I wouldn't want to load the description of all models in `stg_nodes` for example but could maybe find an alternative based on your needs.

**Comment by chaos87** [comment]
I'm actually working on a custom data catalog. Getting these descriptions in BQ and then display them nicely on Notion or other UI
