### ISSUE TITLE
Documentation and test coverage for custom types

### ISSUE THREAD

**Issue by nszoni** [dbt-labs/dbt-project-evaluator#181]
### Describe the feature

Currently, the `fct_documentation_coverage`  and `fct_test_coverage` models require users to have a 'marts' model type/folder in their project. Otherwise, the associated test will return an error with a division by zero.

CTE in the model where 'mart' is hard-coded.

```
conversion as (
    select
        resource_id,
        case when is_described then 1.0 else 0 end as is_described_model,
        case when model_type = 'marts' then 1.0 else NULL end as is_marts_model,
        case when is_described and model_type = 'marts' then 1.0 else 0 end as is_described_marts_model

    from models
),
```
I would like to be able to override the baked-in value for fact models and customize is through the `dbt_project.yml` file, just as in case of  tests.

### Describe alternatives you've considered
My first though is to keep it in a `{{ var("mart_alias", "marts") }}`, which can be driven via project config, but still has it's default value.

### Additional context
This is a universal issue. It can also be the case that you (dbt Labs) want to enforce people using the same conventions, but still would be great to customize.

### Who will this benefit?
It would benefit those who want to tailor the evaluator to fit their folder structure. Personally, I'm not able to see these coverage percentages without having a folder named 'mart'

### Are you interested in contributing this feature?

Absolutely! Although I might need a hand in finding out the best way we can tackle this.

**Comment by graciegoheen** [comment]
Good catch! I just opened a PR to loop through all model types (listed in the `model_types` variable in your dbt_project.yml file) and return a field for coverage for _each_ model type. Let me know if that would solve your issue!

**Comment by nszoni** [comment]
Looks good to me @graciegoheen! Thanks for the quick fix ⚡. I will also check the functionality no later than end of next week:)
