### ISSUE TITLE
Include dbt_utils.unique_combination_of_columns and expression for missing_primary_key_tests

### ISSUE THREAD

**Issue by Kratzbaum92** [dbt-labs/dbt-project-evaluator#192]
### Describe the feature
Currently the missing_primary_tests only checks for the uniqueness test of a single column.

It would be great to include these options:
https://docs.getdbt.com/faqs/tests/uniqueness-two-columns

**Comment by b-per** [comment]
Hi @Kratzbaum92 and thanks for the report!

Our recommendation when the key is a combination of columns is in the vast majority of cases to create a surrogate key (SK) using the combination of columns and defining `unique` and `not_null` tests on this new column.

In your case, it would be difficult for example to test the `non_null` part for multiple columns to make sure that they are proper surrogate keys.

We might revisit it later but for now we are keen to keep the tests as `unique` and `not_null`.

If you want to add exceptions to the errors showing from the package you can also use the new feature [that allows loading those in a seed](https://github.com/dbt-labs/dbt-project-evaluator#configuring-exceptions-to-the-rules).

**Comment by dave-connors-3** [comment]
This came up again in #221 ! flagging this as a good issue to priortize once we an agree on a strategy here.

**Comment by TimNapierVST** [comment]
Yep please include unique combination of columns in uniqueness, for data vault satellites its a must
