### ISSUE TITLE
Rules models all fail since upgrading to 0.1.2 (Postgres)

### ISSUE THREAD

**Issue by qmoret** [dbt-labs/dbt-project-evaluator#193]
### Steps to reproduce
Upgrade to 0.1.2
Run with `dbt build --select package:dbt_project_evaluator --vars 'evaluator: true'`
I have also tried adding an exception seed with an example but no luck.

### Expected results
Rules models should run without error (actual behavior with 0.1.2)

### Actual results
All rules model fail with the same Database error, example below

### Screenshots and log output
Example : 
```
16:15:35  Database Error in model fct_model_naming_conventions (models/marts/structure/fct_model_naming_conventions.sql)
16:15:35    invalid input syntax for type integer: "fct_model_naming_conventions"
16:15:35    LINE 8: where fct_name = 'fct_model_naming_conventions'
```

### System information
packages:
  - package: dbt-labs/dbt_utils
    version: [">=0.8.0", "<0.9.0"]
  - package: dbt-labs/dbt_project_evaluator
    version: 0.1.2

**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.0
  - latest:    1.2.0 - Up to date!

Plugins:
  - redshift: 1.2.0 - Up to date!
  - postgres: 1.2.0 - Up to date!
```

**Comment by graciegoheen** [comment]
Thanks for catching this bug. I think this is an issue with the column types when the seed file is empty. I will dig into this further. 

In the meantime, when you added an exception seed with an example - can you confirm that you deactivated the original seed:

```
seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false
```
  
And ran both the package models and the seed file?

```
dbt build --select package:dbt_project_evaluator dbt_project_evaluator_exceptions 
```

**Comment by qmoret** [comment]
Oh I hadn't run the seed file. But I get a similar issue, on the seed run this time : 
```
07:49:16  Database Error in seed dbt_project_evaluator_exceptions (seeds/dbt_project_evaluator_exceptions.csv)
07:49:16    invalid input syntax for type integer: "fct_multiple_sources_joined"
07:49:16    LINE 3:           ('fct_multiple_sources_joined','child','stg_%_unio...
```

**Comment by b-per** [comment]
I think that you need to add `--full-refresh` as well to "reset" the columns type of the seed (as some columns have been created as `int` already):
```
dbt build --full-refresh --select package:dbt_project_evaluator dbt_project_evaluator_exceptions 
```

**Comment by qmoret** [comment]
That works, thanks!
