### ISSUE TITLE
Macro dbt_utils.star causes source fanout rule warning

### ISSUE THREAD

**Issue by qmoret** [dbt-labs/dbt-project-evaluator#196]
### Describe the bug
When using the `dbt_utils.star` macro in a staging model, there are two references to the source that are captured by the source fanout rule, for instance :
```
parent	model_children
prod.murfy_erp_collectionfile	stg_murfy_erp__collectionfiles, stg_murfy_erp__collectionfiles
```

### Expected results
I would like this to be accepted.
I know I could add an exception on the source but I would still like to check if it is referenced elsewhere.

### System information
v0.1.2

**Which database are you using dbt with?**
- [x] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**Comment by b-per** [comment]
Thanks @qmoret !
We will have a look.

**Comment by dave-connors-3** [comment]
hey @qmoret -- can you give a bit more detail into the model code you have in this staging model? Curious to see how the `star` macro ends up with two references to the source! Having even some pseudocode would help us replicate this issue
