### ISSUE TITLE
Migrate current integration tests to pytest

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#197]
### Describe the feature
In order to mirror the approach of dbt core as well as the rest of the package ecosystem, we should consider moving our test suite to `pytest`. This also gives us more flexibility to add test scenarios without having to maintain multiple dbt projects with specific characteristics of interest (i.e. `integration_tests` vs `integration_tests_2`)

### Describe alternatives you've considered
Continuing to use nested dbt projects

### Who will this benefit?
Developers and maintainers! 

### Are you interested in contributing this feature?
Certainly part of it!

**Comment by b-per** [comment]
@dave-connors-3 , do you have a list of repos that use `pytest` today instead of an `integration_tests` project? `dbt-core` is doing it but I checked quickly `dbt-utils` and it looks like it hasn't moved to `pytest` yet (and personally that would be the one I would try to replicate from)

**Comment by dave-connors-3** [comment]
utils should have [some](https://github.com/dbt-labs/dbt-utils/tree/main/tests), but these may just be ported over from core as they migrated the cross db utils. 

[Metrics also has pytest based testing](https://github.com/dbt-labs/dbt_metrics/tree/main/tests)

**Comment by graciegoheen** [comment]
We should still do this!
