### ISSUE TITLE
Table name `fct_multiple_sources_joined` could be misleading as it includes unioned sources as well

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-project-evaluator#20]
The table `fct_multiple_sources_joined` contains the models joining from multiple sources, as expected, but it also contains models that are unioning from multiple sources (which in some cases might make sense).

We could potentially rename the model from `fct_multiple_sources_joined` to `fct_multiple_sources_joined_or_unioned`. But at the same time, it would be good to have a way to flag the unions vs joins.

In our Internal Analytics project the current convention is to prepend the stg/base model name with `unioned`

**Comment by graciegoheen** [comment]
Do we still want to rename this model?

**Comment by b-per** [comment]
I feel like it, yes. A few ideas for new names:
- `fct_multiple_sources_used_in_model`
- `fct_multiple_sources_in_single_model`
- `fct_multiple_sources_in_model`

The initial discussion about `union` vs `join` and the "flag" is already available with the ability to define exceptions now. So people could easily exclude all the `%_unioned` from being reported.
