### ISSUE TITLE
Uniqueness Tests

### ISSUE THREAD

**Issue by TimNapierVST** [dbt-labs/dbt-project-evaluator#221]
### Describe the feature
Extend or make configurable uniqueness test so it recognises unique_combination_of_columns from dbt_utils

### Describe alternatives you've considered
Making a single unique column on the table

### Additional context
No

### Who will this benefit?
People who use dat-vault in particular for satellite models. Additionally fact tables in dimensional marts

**Comment by dave-connors-3** [comment]
Hey @TimNapierVST ! Thanks for opening up this issue. This is actually already being discussed in another open issue over in #192 ! I am going to close this issue to keep the conversation in one place, but definitely jump over there to add comments for your use case as well!
