### ISSUE TITLE
Request for v0.1.5 release

### ISSUE THREAD

**Issue by waligob** [dbt-labs/dbt-project-evaluator#223]
### Describe the feature
A v0.1.5 package that contains the latest bugfixes.

### Describe alternatives you've considered
I could update our `dbt_packages.yml` to point at git commit https://github.com/dbt-labs/dbt-project-evaluator/pull/219/commits/36d5950a805fbc580eeec98aaf314e1586cdd714 (fixes https://github.com/dbt-labs/dbt-project-evaluator/issues/215) instead of the [recommend installation method](https://docs.getdbt.com/docs/building-a-dbt-project/package-management#hub-packages-recommended) (dbt Hub)

### Additional context
N/A

### Who will this benefit?
Users affected by https://github.com/dbt-labs/dbt-project-evaluator/issues/215

### Are you interested in contributing this feature?
N/A

**Comment by dave-connors-3** [comment]
hey @waligob! we are planning a `0.2.0` release this week ahead of Coalesce with these changes -- thanks for the nudge!
