### ISSUE TITLE
Support other primary key definitioms

### ISSUE THREAD

**Issue by ttusing** [dbt-labs/dbt-project-evaluator#231]
### Describe the feature
Currently, [fct_missing_primary_key_tests](https://github.com/dbt-labs/dbt-project-evaluator/blob/main/models/marts/tests/fct_missing_primary_key_tests.sql) checks if a model has a primary key based on having a `not_null` and `unique` test. These tests could both potentially apply to a non-primary key, or a different test could be used to verify a primary key. Saliently for me, I am using the [primary key test in DBT Constraints from Snowflake Labs](https://github.com/Snowflake-Labs/dbt_constraints/tree/0.5.2/#installation) and not unique/not_null.

It would be great if I could pass a test name as a project variable that matches my primary key test name to work with the primary key test coverage in this package.

[Additional field for other primary key definitions could be parsed here](https://github.com/dbt-labs/dbt-project-evaluator/blob/ad8440b50d201526fc94b9484784f71b608f07f0/models/marts/core/int_all_graph_resources.sql)

### Describe alternatives you've considered
Disabling/overriding models in this package with my custom model. This is very inconvenient and may be incompatible with future changes.

### Who will this benefit?
This will certainly benefit users of DBT constraints.

### Are you interested in contributing this feature?
Yes, happy to add this feature if it is supported by the package authors.

**Comment by dave-connors-3** [comment]
hey @ttusing!

Thanks for the report. Given that this has come up in two other issues (#221 #192), it seems like this may be worth pursuing! 

I think you're idea for a variable to set the test name could be a good one -- let me circle with the team and see what they think!
