### ISSUE TITLE
allow users to run package on subsets of their project

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#232]
### Describe the feature
Users with large projects are unable to run the package, as the templated SQL from the `unpack` macros result in too many lines of SQL for their warehouses to execute. 

[Report in Slack](https://getdbt.slack.com/archives/C046EL9GCJU/p1668109404562609)

### Describe alternatives you've considered

Leaving it as it!

### Additional context

Currently known limit on BigQuery is 1024.00K characters. Will need to also research limits on other warehouses. 

May be able to leverage [selected_resources](https://docs.getdbt.com/reference/dbt-jinja-functions/selected_resources) jinja variable to achieve this! 

### Who will this benefit?
Users with large projects!

**Comment by rsanjabi** [comment]
Running into the same issues with Redshift on a 250 model , 2000 test, 350 sources creates a 74k line stg_nodes_relationship model, which is prohibitive to run. Short term I'm ignoring node tests by adding logic to `get_relationship` and `get_nodes` macros.

`{% set nodes_list = graph.nodes.values() | rejectattr("resource_type", "equalto", "test") %}`
