### ISSUE TITLE
Evaluate specific folder/file(s) to make remediation easier

### ISSUE THREAD

**Issue by jschintz-windriver** [dbt-labs/dbt-project-evaluator#234]
### Describe the feature
When a project is old and littered with issues, provide a path for incremental improvements, focusing on keeping new code clean.  
2 options:
- Allow users to choose which folders/sub-folders are evaluated.
- Only evaluate the modified files and related.

### Describe alternatives you've considered
Is this a custom use case that the repository just needs forked?
Just start a new project from scratch?

### Who will this benefit?
Devs frequently inherit old code that never considered dbt best practices.
That legacy code is just too much to fix at once.  100s of models which lack file structure, naming conventions, tests, docs or even refs.
Allow users to specify a clean slate for future-state.  Mainly a CI use case.

### Are you interested in contributing this feature?
Sure!

**Comment by rsanjabi** [comment]
+1 ing 

We're currently getting around legacy code that breaks rules by enabling/disabling rules for the entire repo until we are able to refactor and get it to pass. But having more sophisticated approaches for evaluation would be helpful.

**Comment by b-per** [comment]
Hi @jschintz-windriver and @rsanjabi 

In case you want to see if this would work for your use case you could try out the version in [feature-allow-excluding-models-packages](https://github.com/dbt-labs/dbt-project-evaluator/tree/feature-allow-excluding-models-packages) (not released to the Hub yet).

Any feedback would be great!

**Comment by jschintz-windriver** [comment]
Thanks @b-per .  This worked well for me.
I appreciate your team building this feature.  And the project-evaluator package in general has gretaly helped herd my stubborn cats.
