### ISSUE TITLE
large project causes SQL compilation error for stg_node_relationships

### ISSUE THREAD

**Issue by cladden** [dbt-labs/dbt-project-evaluator#239]
### Describe the bug
Running (in snowflake) against a project with many model relationships (e.g. 3700 models that have > 16,384 individual relationships), the stg_node_relationships model fails with the following SQL compilation error:

``` 
Database Error in model stg_node_relationships (models/staging/graph/stg_node_relationships.sql)
15:24:00    SQL compilation error: error line 7 at position 20
15:24:00    maximum number of expressions in a list exceeded, expected at most 16,384, got 16,515
15:24:00    compiled Code at target/run/dbt_project_evaluator/models/staging/graph/stg_node_relationships.sql
```

Snowflake has some recommendations to fix this issue: https://community.snowflake.com/s/article/maxi-expressions-exceeded

### Steps to reproduce
Create a project with many >3700 models, run `dbt build --select package:dbt_project_evaluator`

### Expected results
Expect no SQL compilation errors for stg_node_relationships

### Actual results

```
Database Error in model stg_node_relationships (models/staging/graph/stg_node_relationships.sql)
15:24:00    SQL compilation error: error line 7 at position 20
15:24:00    maximum number of expressions in a list exceeded, expected at most 16,384, got 16,515
15:24:00    compiled Code at target/run/dbt_project_evaluator/models/staging/graph/stg_node_relationships.sql
```

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ X ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0
  - latest:    1.3.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Up to date!
```

**Comment by dave-connors-3** [comment]
hey @cladden ! Thanks for opening the issue -- we have another similar request over in #232 -- the package currently breaks down with sufficiently large projects, and we're actively investigating a change to the materialization of the `unpack` models to get around this issue. Stay tuned!

**Comment by cladden** [comment]
Thanks for the quick response! Glad to hear this is being worked on and I will keep an eye out for updates. 

In the meantime, here is a hacky code change I used to overcome the issue in [macros/unpack/get_nodes.sql](https://github.com/cladden/dbt-project-evaluator/commit/e3802897f3b4121fb6943d8a41440eee957f1db6), this adds an environment variable that selects specific nodes when the file path "contains" the given pattern in the env var.
