### ISSUE TITLE
Handle/flag hard-coded references

### ISSUE THREAD

**Issue by deanna-minnick** [dbt-labs/dbt-project-evaluator#240]
### Describe the feature
I would love for this package to be able to handle (and flag?) hard-coded references (ie `raw.stripe.payment` vs. `{{ source ('stripe', 'payment') }`). I specifically noticed that 'fct_unused_sources` currently returns sources that are accessed only via hard-coded references instead of the `source` or `ref` macros. There may be other applications for this functionality within the package as well.

### Describe alternatives you've considered
The minimum response to this issue would be to add a note to the `readme` regarding the results of the `fct_unused_sources` model to include this possibility. A value-add in that documentation could be a recommendation about how to discern whether the sources are truly unused vs. accessed through hard-coding. For instance, in my case I used the list generated by `fct_root_models` as a starting place when looking for hard-coded references.

### Additional context
This should apply to multiple databases.

### Who will this benefit?
This would benefit anyone with hard-coded references in their project, allowing them to systematically transition to appropriate alternatives (`source` and `ref` functions). 

### Are you interested in contributing this feature?
Sure! And I'd be glad for some discussion/input around how to approach solving this.

**Comment by graciegoheen** [comment]
Hi! Didn't realize we already have an old issue about [this](https://github.com/dbt-labs/dbt-project-evaluator/issues/189) - let's move discussion over there. I'm going to try to tackle this today.
