### ISSUE TITLE
Additional output on warning/errors

### ISSUE THREAD

**Issue by gictor** [dbt-labs/dbt-project-evaluator#251]
### Describe the feature

As a DBT Project Evaluator user 
I would like additional output on my warning/errors
So that I don't have to switch context to find where the issues inherit from

Example

```
14:05:37  Warning in test dbt_utils_accepted_range_fct_documentation_coverage_documentation_coverage_pct___var_documentation_coverage_target_ (models/marts/documentation/documentation.yml)
14:05:37    Got 1 result, configured to warn if != 0
14:05:37  
14:05:37    <resource_name> <model_type>
14:05:37    <resource_name> <model_type>
14:05:37    <resource_name> <model_type>
14:05:37    <resource_name> <model_type>
```

### Describe alternatives you've considered
Instead of having this feature inside of DBT Project Evaluator we could run a small script afterwards to print output from the fact models.

### Additional context
We use BigQuery, but the feature would be beneficial to all databases.

### Who will this benefit?
Any DBT Project Evaluator user that does not follow best practice. No warnings, no benefits.

### Are you interested in contributing this feature?
Yes, we are willing to try but we would need some advice on where this feature would fit in to the code base.

**Comment by b-per** [comment]
Hi @gictor! 

The first idea that comes to mind would be to create a macro that would run as part of an `on-run-end` hook and would use `run_query()` (and most likely the `results` and/or `graph` objects) to query the different fact tables and then print them out in the console.

The macro would use a couple of Jinja loops to go through all the different `fct` tables.

Would it be something that you would be keen trying to develop? Feel free to create a Draft PR, even if it is not completely working, if you want to get some feedback at some point.
