### ISSUE TITLE
ENABLE_DBT_PROJECT_EVALUATOR value is not correctly interpreted as bool

### ISSUE THREAD

**Issue by rory-donaldson** [dbt-labs/dbt-project-evaluator#256]
### Describe the bug
ENABLE_DBT_PROJECT_EVALUATOR value is not correctly interpreted as bool

### Steps to reproduce
Using the example from the readme gives the error.
The error also occurs when actually setting the env var on the CLI by
`export ENABLE_DBT_PROJECT_EVALUATOR=false` and also by `export ENABLE_DBT_PROJECT_EVALUATOR=true` 
```
# dbt_project.yml

models:
  dbt_project_evaluator:
    +enabled: "{{ env_var('ENABLE_DBT_PROJECT_EVALUATOR', 'true') }}"
```
Running with dbt v1.3.0 and dbt-project-evaluator v0.2.1

### Expected results
Expected that the variable is correctly read as a boolean value, both when actually set, and when the default value is being used.

### Actual results
A validation error is raised

### Screenshots and log output
```
  File "/Users/rory.donaldson/.pyenv/versions/3.9.7/lib/python3.9/site-packages/hologram/__init__.py", line 989, in validate
    raise ValidationError.create_from(error) from error
hologram.ValidationError: 'false' is not of type 'boolean'

Failed validating 'type' in schema['properties']['enabled']:
    {'default': True, 'type': 'boolean'}

On instance['enabled']:
    'false'
```
### System information
**The contents of your `packages.yml` file:**

```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.9.2
  - package: dbt-labs/codegen
    version: 0.8.1
  - package: dbt-labs/dbt_project_evaluator
    version: 0.2.1

```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.0
  - latest:    1.3.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery:  1.2.0 - Not compatible!
  - snowflake: 1.3.0 - Up to date!```

**Comment by b-per** [comment]
Hi!

I don't think that this is an issue with the package itself but more about how Jinja is interpreted in dbt.

Could you try:
```
# dbt_project.yml

models:
  dbt_project_evaluator:
    +enabled: "{{ env_var('DBT_ENABLE_DBT_PROJECT_EVALUATOR', 'true') == 'true' | as_bool }}"
```

**Comment by rory-donaldson** [comment]
That works perfectly thank you! PR #257 raised now to update the README
