### ISSUE TITLE
Project Evaluator Incapable of Running on Larger Projects

### ISSUE THREAD

**Issue by jsteele-om1** [dbt-labs/dbt-project-evaluator#268]
### Describe the bug
Running in a project that contains ~3,700 models causes the recursive query in the `int_direct_relationships` model to hang.  There query does not error out, but it stops making progress (XL warehouse in snowflake for four hours).  It had about 35 billion rows output from the recursive CTE at this time.

### Steps to reproduce
Create a project with many >3700 models, run `dbt build --select package:dbt_project_evaluator`

### Expected results
1. It's possible to run `dbt build --select package:dbt_project_evaluator` on a large project
2. User can scope the project evaluator to specific directory or model selector.

### Actual results
There was no output from this issue because the query did not fail, it is just unable to continue to make progress.

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
$ dbt --version
Core:
  - installed: 1.3.0
  - latest:    1.3.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Up to date!

```

### Are you interested in contributing the fix?

**Comment by dave-connors-3** [comment]
hey @jsteele-om1 ! this is a known issue and common request! we are working on a solution and hope to have one released in the new year!

**Comment by jsteele-om1** [comment]
> hey @jsteele-om1 ! this is a known issue and common request! we are working on a solution and hope to have one released in the new year!

Thank you, appreciate the information and follow up with linked PR
