### ISSUE TITLE
Add escape_single_quotes shim to spark adapter

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-project-evaluator#269]
This should eventually be added to the spark adapter!

_Originally posted by @graciegoheen in https://github.com/dbt-labs/dbt-project-evaluator/pull/246#discussion_r1053726450_

**Comment by graciegoheen** [comment]
PR has been opened in dbt-spark https://github.com/dbt-labs/dbt-spark/pull/573

**Comment by dbeatty10** [comment]
https://github.com/dbt-labs/dbt-spark/pull/573 has been merged 🎉 and it is listed in the changelog [here](https://github.com/dbt-labs/dbt-spark/blob/8e089e4882098dc051c5c897cb559ec78890b7c8/CHANGELOG.md).

What would be the trade-offs of removing this file?
- [macros/cross_db_shim/spark_shims.sql](https://github.com/dbt-labs/dbt-project-evaluator/blob/7203c674148a13550b6baed2accad8e25e6f1489/macros/cross_db_shim/spark_shims.sql)

**Comment by dave-connors-3** [comment]
@dbeatty10 I think there would be limited issues! We'd need to make sure to also update the required dbt version once that's released into the wild to ensure users of this package use 1.4 and above

**Comment by dbeatty10** [comment]
Cool! Timing and strategy up to y'all, of course.

**Comment by dbeatty10** [comment]
> @dbeatty10 I think there would be limited issues! We'd need to make sure to also update the required dbt version once that's released into the wild to ensure users of this package use 1.4 and above

I just updated the "implementation hints" here to reflect bumping up to 1.4:
- https://github.com/dbt-labs/dbt-project-evaluator/issues/287
