### ISSUE TITLE
Increase dependency of dbt_utils to >=1.0.0

### ISSUE THREAD

**Issue by Surbias** [dbt-labs/dbt-project-evaluator#273]
### Describe the feature
I currently need to use dbt_utils `1.0.0` to use certain features (specifically `dbt_utils.not_empty_string`).

I would like to add `dbt-project-evaluator` to the existing project without having to downgrade `dbt_utils` and remove certain tests.

### Describe alternatives you've considered
No alternatives possible as currently `dbt-project-evaluator` must have version `<1.0.0` of `dbt_utils`

### Who will this benefit?
Anyone using the latest features from dbt_utils `>=1.0.0`

### Are you interested in contributing this feature?
I am interested in helping to contribute, if this is something I can do please let me know. However I have noticed that [this change](https://github.com/dbt-labs/dbt-project-evaluator/blob/main/packages.yml#L3) is already in the `main` branch.
As such the actually fix for this is to release a new version with the latest `main`.

**Comment by dave-connors-3** [comment]
This should be resolved with the latest release! @Surbias
