### ISSUE TITLE
stg_nodes times out

### ISSUE THREAD

**Issue by macklin-fluehr** [dbt-labs/dbt-project-evaluator#274]
### Describe the bug

stg_nodes doesn't seem to work, or at least seems to hang. 

To give more context, stg_sources took 4 seconds to run. The table build for stg_nodes timed out 25 minutes later. We don't have a particularly large number of models (< 1000, source count is similar).

### Steps to reproduce

dbt run -s package:dbt_project_evaluator

dbt version 1.3.1
dbt_project_evaluator version 0.3.0
WHSE: Amazon Redshift

### Expected results
stg_nodes takes a similar amount of time to build as stg_sources

### Actual results
stg_nodes times out after 25 minutes of not completing

### Screenshots and log output
<img width="827" alt="Screen Shot 2022-12-28 at 5 05 27 PM" src="https://user-images.githubusercontent.com/35469749/209877025-1941ed30-abb6-4dd9-98f2-ac4f09e2e94b.png">

### System information
```
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: dbt-labs/codegen
    version: ">=0.6.0"
  - package: dbt-labs/dbt_project_evaluator
    version: 0.3.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.3.1
```

### Additional context

not sure what could be the hang up. not sure if it is redshift specific that the regex is really slow in `find_all_hardcoded_references`?

### Are you interested in contributing the fix?
Potentially

**Comment by dave-connors-3** [comment]
hey @macklin-fluehr ! Thanks for opening the issue, we're definitely keen to dig into this. A few follow up questions

1. can you confirm the exact resource counts in your project?
2. was this the first time running the project? or did this issue appear only after upgrading to the latest version?
3. Is there anything notable in the compiled code? how large are the compiled sql files?

We do have outstanding reports of projects of a certain size being unable to build certain models, but generally the error raised is a bit more specific.

**Comment by macklin-fluehr** [comment]
1. 
Models: ~350
Tests: ~4500
Sources: ~270

2. First time running with the project
3. Compiled, most models are under 100 lines. 4 are about 500 lines long. Which doesn't sound too crazy.

While we only have 350 models, I would say that the dependency graph is pretty dense in a lot of places, so maybe in this case 350 is a lot? I'd also wonder if it's specific to redshift. Reading through other cases where the project failed to load, I don't think they had used redshift.

**Comment by macklin-fluehr** [comment]
@dave-connors-3 , I upgraded to 4.1, but immediately got a database error upon running `dbt build --select package:dbt_project_evaluator`

<img width="953" alt="Screenshot 2023-02-04 at 11 35 22 AM" src="https://user-images.githubusercontent.com/35469749/216778828-af1041b9-afc6-40df-aadb-195fe4b436dc.png">

**Comment by dave-connors-3** [comment]
hey @macklin-fluehr ! It looks like you're using Redshift -- you'll need to add the dispatch [configuration shown here in the readme](https://github.com/dbt-labs/dbt-project-evaluator/blob/main/README.md#additional-setup-for-databrickssparkduckdbredshift):

```yml
# dbt_project.yml

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']
```

This should be a top level key, and can't be nested under any other configuration! Let me know if that resolves the issue

**Comment by macklin-fluehr** [comment]
ah. my mistake. must have missed it. Seems to be working now!
