### ISSUE TITLE
Change `hard_coded_references` to array

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#290]
### Describe the feature

in #265 , we had to add a Redshift shim to ensure we could fit the hard coded references into our stg models unpacking the graph. In a desire to avoid having to override `type_string` in the future for redshift users, one possible solution is to change this field to an array type.

checkout the branch called `array-hard-coded-references` for the latest attempt!

### Describe alternatives you've considered
Leaving this alone!

### Who will this benefit?
Redshift users who use `type_string()`

**Comment by graciegoheen** [comment]
Note: VALUES does not support ARRAY_CONSTRUCT expression for snowflake
