### ISSUE TITLE
fct_model_directories bug

### ISSUE THREAD

**Issue by DVDylanRoe** [dbt-labs/dbt-project-evaluator#302]
### Describe the bug
fct_model_directories stores records for all the models that are not considered to be located appropriately in your porject according to the configuration of model types, folder names. If a model only belongs to a directory called Y_X' and another directory called 'X' is present and defined as a model type folder name in the dbt_project yml file then the dbt project evaluator believes it should appear under the directory called 'X' therefore producing a warn in the is_empty_fct_model_directoris test.

### Steps to reproduce
In a dbt project add version 0.4.0 of the dbt project evaluator to your dbt packages yml file and run `dbt deps`

In your dbt project yml file configure variables for the project evaluator as below

```
vars:
dbt_project_evaluator:  
    model_types: ['X', 'Y_X']
    X_folder_name: 'X'
    X_prefixes: ['X_']
    Y_X_folder_name: 'Y_X'
    Y_X_prefixes: ['Y_']
```

Create two directories 'X' and 'Y_X' and under the 'Y_X' folder create a model called 'Y_X_model.sql'

run `dbt build -s package:dbt_project_evaluator` 

### Expected results
As the 'Y_X_model.sql' is placed under the correct directory the 'is_empty_fct_model_directories' test should pass

### Actual results
The test presents a warn with a count of 1. The 1 record is obviously the 'Y_X_model.sql'.

![image](https://user-images.githubusercontent.com/112865326/216955271-89df529c-39be-4d10-944f-a8238a7c4372.png)

I believe the bug comes from a combination of lines 62 to 66 ,

`case 
            when unioned_with_calc.resource_type in ('test', 'source', 'metric', 'exposure', 'seed') then null
            when {{ dbt.position('naming_convention_folders.folder_name_value','unioned_with_calc.directory_path') }} = 0 then null
            else naming_convention_folders.model_type 
        end as model_type_folder,`

line 115',

`row_number() over (partition by resource_id order by position_folder desc) as folder_name_rank`

and line 123  all in 'int_all_graph_resources.sql'

`where folder_name_rank = 1`

As 'X' appears in the folder name 'Y_X', two records appear with non_null value in the model_type_folder field. 
And 'X' appears later in the directory path so will given the folder_name_rank = 1 which is the criteria for the final selection.

I believe this can be solved by changing the jinja on line 64 to

`{{ dbt.position("concat('/' + 'naming_convention_folders.folder_name_value' + '/', 'unioned_with_calc.directory_path') }}`

Therefore when looking for '/X/' in the directory 'models/Y_X/Y_X_model.sql' the record will return a null value for that record.

### System information

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
Using dbt cloud so dbt v1.3.0-latest

### Additional context
In my actual project the directories causing problems are called 'sats' and 'eff_sats' and there isn't a better naming convention I can use.

**Comment by dave-connors-3** [comment]
hey @DVDylanRoe -- thanks for the thorough investigation here. I think your suggestion to include the slashes to indicate we're searching specifically for a folder is straightforward! Do you have any interest in opening a PR with that suggested change?

**Comment by DVDylanRoe** [comment]
Thank you for the quick reply. I can certainly do that, I'll get onto it now.
