### ISSUE TITLE
allow users to limit output of models by package

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#307]
### Describe the feature

If i am a user of a package that contains models, i may want to exclude those models from DPE checks. Right now, doing so would require use of the exceptions seed, with entries for each combination of model-to-exlude + fct_model_name to make sure not to run any check on any external model (or use of wildcards when that PR is closed)

it would be easier to just declare what set of packages to consider, and have the logic in the models take care of the rest!

### Describe alternatives you've considered

Seed only

### Additional context

[related thread](https://getdbt.slack.com/archives/CU4MRJ7QB/p1676667752771069?thread_ts=1676661048.963109&cid=CU4MRJ7QB)

### Who will this benefit?

- package users
- multi-project deployments in the future

### Are you interested in contributing this feature?

of course i am, me

**Comment by epapineau** [comment]
@b-per [Rumor has it you've got a solution in mind for this?](https://github.com/dbt-labs/dbt-project-evaluator/pull/310#issuecomment-1474025823)

**Comment by b-per** [comment]
I added comments to your PR, but I'd be keen tackling this and [that](https://github.com/dbt-labs/dbt-project-evaluator/issues/234) with a common approach

**Comment by graciegoheen** [comment]
I think we can close this as done - @dave-connors-3 can you confirm?

**Comment by b-per** [comment]
Yes, this is done!
