### ISSUE TITLE
add check to rename schema files to include a leading `_` and resource name

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#312]
### Describe the feature

Per some internal conversation, the community team want to standardize the way folks name their resource yml files. 

Our recommended best practice is using a leading underscore, and including the resource type that is described within the yml file in the filename. For example, for a yml file with model configs, valid names for that file would be:

- _[resource_type].yml
- _[directory name]__[resource_type].yml

The underscore is for discoverability, the resource name for clarity. 

### Describe alternatives you've considered
Do nothing, run wild, be free

### Who will this benefit?

`yml` writers of all kinds

### Are you interested in contributing this feature?

giddy up

**Comment by b-per** [comment]
This could still be useful, no?
