### ISSUE TITLE
[Under the hood] Some table values are populated with 'None' instead of null

### ISSUE THREAD

**Issue by ttusing** [dbt-labs/dbt-project-evaluator#324]
### Describe the bug
While writing some custom tests on DBT project evaluator tables, I found at least one example where I found the unexpected string value `None` instead of a database NULL.

### Steps to reproduce

`select schema from dbt_project_evaluator.int_all_graph_resources where schema='None';`

This returns None for operations and analyses. Ideally it would return null

### Expected results
 I expected to see `null` if the object did not have a value.

### Actual results
`None` was returned. `None` is likely the Python empty value represented as a string. The matching concept in databases is `null`.

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:
```
1.4.5
```

### Are you interested in contributing the fix?
Yep

**Comment by dave-connors-3** [comment]
hey @ttusing ! would welcome a PR here! great callout!
