### ISSUE TITLE
New Rules! for model governance (dbt Core v1.5)

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-project-evaluator#332]
### Describe the feature

https://dbt-labs.github.io/dbt-project-evaluator/0.5/rules/

I'd like to propose some [New Rules](https://dbt-labs.github.io/dbt-project-evaluator/main/rules/), related to the model governance features that are new in v1.5.
- **Public Models Have Contracts:** Every model with `access: public` also has `contract: {enforced: true}`
- **Public Models Are Documented:** Every model with `access: public` has a top-level `description` _and_ `description` for every column ([this rule](https://dbt-labs.github.io/dbt-project-evaluator/main/rules/documentation/#undocumented-models), but more)
- **Column Naming Convention:** For columns in models with explicitly defined contracts, we can assert that columns' names and data types match [our opinionated recommendations](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md#:~:text=Date/time%20columns,is_active_customer%20and%20has_admin_access).
- **Exposures Public Parents:** Exposures depend only on models with `access: public` (similar to [this rule](https://dbt-labs.github.io/dbt-project-evaluator/main/rules/performance/#exposure-parents-materializations))
- **At Most Three Versions:** There should be, at most, three versions of a given model: one `latest`, one `old`, one `prerelease`
- **Group Coverage:** Calculate percentage of resources in `groups`. Groupable resources are everything except `sources` + `exposures`. Raise a warning about resources that aren't in groups, with an owner. (This will be a heavier lift at first; we should build [tooling to make it easier](https://github.com/dbt-labs/dbt-meshify/issues/21)!)
- **Model Access Ratio:** Calculate ratios of model `access`: private, protected, public. My absolutely arbitrary guess at an ideal breakdown would be somewhere in the ballpark of 50/40/10%. Every `group` should have at least one `private` model.

Related to `deprecation_date` (https://github.com/dbt-labs/dbt-core/issues/7433), coming in v1.6:
- All `old` model versions (< `latest_version`) must have a `deprecation_date`
- All models with a `deprecation_date` earlier than today should be removed

Very open to thoughts & feedback on all of the above — and more ideas, of course :)

### Who will this benefit?

Developers & maintainers of large & complex projects, who want to start taking advantage of v1.5 features for model governance

### Are you interested in contributing this feature?

I can help with refining/brainstorming, &/or possibly contribute with some of my hacktime :)

**Comment by graciegoheen** [comment]
Love all of these ideas and am excited to address new best practices for model contracts. Do you think these best practices fall into one of our pre-existing categories (modeling, testing, documentation, structure, performance) or does this call for a new category?

I think some of these fall neatly into modeling (such as Exposures Public Parents) - but for the others, I'm thinking about creating a new category for "governance".

**Comment by b-per** [comment]
In my mind, most of them would fall on a new Governance category. Mostly because contracts/governance is quite opt-in and it would be great for people to activate/deactivate Governance rules if they want or not.

The one that I am less sure about is "Column Naming Convention". While it only really works when governance is in place and all columns are listed, this feels more about modelling that Governance to me.

**Comment by b-per** [comment]
@dave-connors-3 , you were looking at those at some points. Are you OK with closing this issue with the changes you did or do you think there is more work to be done?

**Comment by sadahry** [comment]
How about `fct_public_models_without_exposures` ?

In our teams, all public models have external access, and writing the exposures are sometimes missed.
This new governance is useful to avoid the missing.

If public models without exposures are very rare,
I think it should be into dbt_project_evaluator_exceptions.csv as exception.

Please tell us how do you think about it ..

**Comment by b-per** [comment]
Hi @sadahry , thanks for adding this suggestion!

I don't know if your rule would apply to a majority of use cases.

In my mind, public models are about the ability to `ref()` those models from different dbt groups and/or projects, which is something different from "public" in the sense that those models are consumed outside of dbt by other people and tools.

Internally we define exposures on models that are not public and have public models without exposures.


What I would recommend instead here is for you to create your own custom model and test on top of the models the package is creating (you can check the existing models and tests for inspiration) and you can then run the project evaluator package with `dbt build --select package:dbt_project_evaluator+` (with the `+` after) to pick up the default models/tests and your custom ones

**Comment by sadahry** [comment]
Understood.
I'll create a custom model. Thanks!

**Comment by sadahry** [comment]
Just in case, I'd like to share it.

```sql
with
    public_models as (
        select *
        from {{ ref("dbt_project_evaluator", "int_all_graph_resources") }}
        where resource_type = 'model' and is_public
    ),
    final as (
        select *
        from public_models m
        where
            not exists (
                select 1
                from {{ ref("dbt_project_evaluator", "base_exposure_relationships") }} e
                where m.resource_id = e.resource_id
            )
    )

select *
from final {{ dbt_project_evaluator.filter_exceptions(this) }}
```
