### ISSUE TITLE
Enhance the regex matching for hard coded sources

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-project-evaluator#335]
### Describe the feature

Currently, the macro checking for hard coded sources doesn't work when we read from a table without mentioning the db or schema.

In the example below, `ghj` is a hard coded ref as there is no CTE called `ghj`

```
with abc as (
...
)

, def as (
...
)

select 
    *
from
    abc inner join def on abc.id = def.id
    inner join ghi on ghi.id = abc.id
```

**Comment by dave-connors-3** [comment]
- create list of CTEs ` {{ a word }} as ( .... ) `
- check list of tables `from {{ a word }}`
- check if tables not in list of CTEs
