### ISSUE TITLE
Question: get_custom_alias() with filter_exceptions()

### ISSUE THREAD

**Issue by michaellynton** [dbt-labs/dbt-project-evaluator#341]
I have been testing this package and am loving it. 

Our project overrides the `get_custom_alias macro()` to support multiple developers in one schema. 

For example, if I build` foo.sql` in our `dev` schema, it would get built as `dev.dbt_ml_foo`.

I have exceptions listed out in the `dbt_project_evaluator_exceptions.csv`.  The issue I've run into, is that when using the exceptions, the macro `filter_exceptions()` is using the model name per the target being run, as it's built in the warehouse (in other words, it's searching the exception file for `dbt_ml_fct_model_naming_conventions` instead of `fct_model_naming_conventions`). 

Instead, I want it to strip off my target prefix when using that macro. 

For the time being, I modified the macro, like this 👇 , essentially just replacing `dbt_ml` with an empty string so my exception can be found in the seed file. 
<img width="677" alt="image" src="https://user-images.githubusercontent.com/7647726/236330268-0c54a598-48dd-4b48-b989-d87efbda755e.png">

But, I wanted to see if there's a different way to go about this without modifying the macro. Or I'm even happy to contribute a customization for this macro if that's the best path forward.

**Comment by b-per** [comment]
I think I am a bit confused by the behaviour :-D

`{{ model_ref.name }}` actually returns `dbt_ml_<the_model_name>` after you overwrote `generate_alias_name()`?

I would expect `model_ref.alias` to have this value but not `model_ref.name`.

**Comment by michaellynton** [comment]
I was a little surprised as well, but I figured custom aliases are not as common. 

Here's what `generate_alias_name` looks like, if helpful. 

```yml
{% macro generate_alias_name(custom_alias_name=none, node=none) -%}

{%- if target.name == 'prod' -%}
        {{ node.name }}

{%- else -%}
        {{ target.name }}_{{ node.name }}
{% endif %} 

{%- endmacro %}

```


I just checked again, reverting the macro to the original syntax. When I run, for example, `fct_model_naming_conventions` with `{{ model_ref. name }}` in `filter_exceptions()`, this is the query that's executed from `filter_exceptions()`:

```sql
select
        column_name,
        id_to_exclude
    from DB.DEV.dbt_ml_dbt_project_evaluator_exceptions
    where fct_name = 'dbt_ml_fct_model_naming_conventions'
```

But then if I switch to my modified version, that strips out the target name from the beginning of the model (alias) name, the query looks like:

```sql
select
        column_name,
        id_to_exclude
    from DB.DEV.dbt_ml_dbt_project_evaluator_exceptions
    where fct_name = replace('dbt_ml_fct_model_naming_conventions', 'dbt_ml_' ,'')
```

**Comment by michaellynton** [comment]
This is a wild guess ... but could it be that the `filter_exceptions()` macro in the package, is not 'respecting' the `generate_alias_name()` in my project?
