### ISSUE TITLE
Parsing error when upgrading to dbt v1.5

### ISSUE THREAD

**Issue by belalaboabdo** [dbt-labs/dbt-project-evaluator#342]
### Describe the bug
Package is causing a parsing error for the `fct_test_coverage` having a test set to `None`.

### Steps to reproduce
Set dbt project to v1.5 run
```
dbt clean
dbt deps
dbt seed
```
### Expected results
Full parse completes successfully and csv's are loaded to warehouse.

### Actual results
A parsing error occurs due to a test defined by the `dbt_project_evaluator` package.

### Screenshots and log output
```
Parsing Error
--
  | Invalid models config given in models/marts/tests/testing.yml @ models: {'name': 'fct_test_coverage', 'description': 'this model shows a few key metrics related to how well tested your dbt project is.', 'columns': [{'name': 'test_to_model_ratio', 'description': 'the total number of tests in the project divided by the total number of models in the project', 'tests': None}, {'name': 'test_coverage_pct', 'description': 'the number of models in the project with at least one test configured divided by the total number of models in the project', 'tests': [{'dbt_utils.accepted_range': {'name': 'valid_test_coverage', 'min_value': "{{ var('test_coverage_target') }}", 'severity': 'warn'}}]}], 'original_file_path': 'models/marts/tests/testing.yml', 'yaml_key': 'models', 'package_name': 'dbt_project_evaluator'} - at path ['columns'][0]['tests']: None is not of type 'array'
```

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt=1.5.0
```

**Comment by b-per** [comment]
Hi @belalaboabdo, this has been fixed in 0.5 that we released last week, you will just need to update the version of the package to work with 1.5
