### ISSUE TITLE
print_dbt_project_evaluator_issues bug

### ISSUE THREAD

**Issue by yoheimiyamoto** [dbt-labs/dbt-project-evaluator#343]
### Describe the bug
The macro `print_dbt_project_evaluator_issues` does not return any test failures from this package into the terminal.

### Steps to reproduce
1. Add the following line in `dbt_project.yml`
```yaml
on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
```
2. Add new source in `sources.yaml`
3. Run `run a dbt build --select package:dbt_project_evaluator`

### Expected results
```shell
-- dbt__is_empty_fct_unused_sources_ --
| parent |
| { Unused source name!! } |

```

### Actual results
```
-- dbt__is_empty_fct_unused_sources_ --
| parent |
| ------ |
```

### Screenshots and log output
<img width="260" alt="Screenshot 2023-05-14 at 8 55 13" src="https://github.com/dbt-labs/dbt-project-evaluator/assets/11155406/294552ff-2551-43f3-9b77-3e58309e5f6e">

### System information
```yaml
  - git: "https:///github.com/dbt-labs/dbt-project-evaluator"
    revision: v0.6.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```shell
Core:
  - installed: 1.4.6
  - latest:    1.5.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.4.3 - Update available!
```

### Additional context
I was able to confirm that the error was saved in the table `dbt__fct_unused_sources`.

**Comment by yoheimiyamoto** [comment]
@b-per 

Yes. I am using `generate_alias_name()`. Is it possible to use both `generate_alias_name` and `dbt_project_evaluator` ?

`macros/get_custom_alias.sql`
```
{% macro generate_alias_name(custom_alias_name=none, node=none) -%}
    {% if target.name == 'dev' and var('developer_name') != '' %}
        dbt_{{var('developer_name')}}__{{ node.name }}
    {%- else -%}
        dbt__{{ node.name }}
    {% endif %}
{%- endmacro %}
```

**Comment by b-per** [comment]
It looks like there is a bug right now when using `print_dbt_project_evaluator_issues` but I am quite sure that it will be possible to fix it somehow.
