### ISSUE TITLE
Comments count as hardcoded references

### ISSUE THREAD

**Issue by epapineau** [dbt-labs/dbt-project-evaluator#346]
### Describe the bug

Lines that are commented out are considered in `fct_hard_coded_references`. We had two failures in our project triggered by the following comments:

```
-- SL eligible from 1.2 onward
```

```
--prework/start had null develop request id that was then filled
--e.g. select * from analytics.stg_dbt_cloud__ide_refresh_lifecycle
--     where startup_id = '8f9330cc-f76a-4a5e-97fd-a2fb8fc90ea7'`
```

### Steps to reproduce

Include a commented out hardcoded reference like the examples above

### Expected results

Commented out code does not count towards hard coded references

### Actual results

Commented out code does count towards hard coded references

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
<output goes here>
```
We're on 1.4.6

**Comment by b-per** [comment]
I don't think we will be able to fix those and you might have to list those as exceptions with a comment that this is because of the regex matching. Handling this use case is going to be tough with regexes.

**Comment by epapineau** [comment]
Since they were just comments in our project I changed the language to avoid the flag, but I figured I'd raise an issue for y'all.

RE: handling with regexes, could you separate regex by into groups, separating groups by `--` or `//`, and only evaluate the group not proceeded by a comment?
