### ISSUE TITLE
Update metric YAML for dbt-core 1.6+

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-project-evaluator#355]
### Describe the bug

The spec of the YAML for dbt_metrics and metricflow is completely different so dbt-core 1.6+ is breaking on compile (as we have a metric defined in the integration tests for this package). 

We should update this metric definition to use the new syntax.

**Comment by b-per** [comment]
There are actually more issues than anticipated as the macro `get_metric_values` fails as well, as the new metric don't have a `model` field defined.
