### ISSUE TITLE
Hard Coded References interaction with dbt-python (Snowpark)

### ISSUE THREAD

**Issue by LisandroCocca** [dbt-labs/dbt-project-evaluator#357]
## Context
When using [dbt-python](https://docs.getdbt.com/docs/build/python-models) there is usually the necessity of importing packages.

## Problem
In the `fct_hard_coded_references` table I get a list of all the packages imported as an "error". 
For example:
- from {package} import {function} generates an entry on the hard_coded_references list, indicating {package}

## Desired Output
It would be nice to skip python imports when executing this check

**Comment by Esya** [comment]
Steps to reproduce, create a model.py file 

```
from pyspark.sql.window import Window

.... any python model here ...
```

```
-- is_empty_fct_hard_coded_references_ --
| model            | hard_coded_references |
| ---------------- | --------------------- |
| pipeline_history | pyspark.sql.window    |
```

**Comment by dave-connors-3** [comment]
thanks for the report! I think we can likely skip python models altogether for this check!
