### ISSUE TITLE
Enable primary key test coverage for resource types outside of models

### ISSUE THREAD

**Issue by ttusing** [dbt-labs/dbt-project-evaluator#358]
### Describe the feature
It would be great to be able to assert that my sources have primary keys defined. It would also be useful for snapshots and seeds. This looks like it would be a relatively easy change.

### Describe alternatives you've considered
I could not do this or write the model outside of the package.

### Who will this benefit?
Users who expect primary key assertions on tables that are not DBT models.

### Are you interested in contributing this feature?
Yes! here is a forked repo with the commit that implements this (can make this a PR) https://github.com/dbt-labs/dbt-project-evaluator/compare/main...ttusing:dbt-project-evaluator:main

**Comment by graciegoheen** [comment]
This sounds awesome! Thoughts on another implementation strategy where there's a configurable way to tell `dbt_project_evaluator` which `resource_type`s should be included in the test coverage checks?

**Comment by ttusing** [comment]
> This sounds awesome! Thoughts on another implementation strategy where there's a configurable way to tell `dbt_project_evaluator` which `resource_type`s should be included in the test coverage checks?

Yes! I think this is a good pattern. I will give it a shot.
