### ISSUE TITLE
Add model version to test output

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#378]
### Describe the feature
Right now, we report the model name for any rule violation. This can lead to misleading results if it's a specific version of a model that violates the rule in question, or if multiple versions of a model both violate a rule and we only report the name.  We should 

1. pull in `version` from the `graph` in `stg_nodes` 
2. add it to any model that uses `name` in the output and explicitly checks model nodes

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

**Comment by graciegoheen** [comment]
@epapineau relevant to our convo!

**Comment by graciegoheen** [comment]
@dave-connors-3 is this complete?
