### ISSUE TITLE
compile error in redshift when configuring exceptions to the rules

### ISSUE THREAD

**Issue by GavinChowUp** [dbt-labs/dbt-project-evaluator#384]
Hi team, I fllowed the [doc](https://dbt-labs.github.io/dbt-project-evaluator/0.8/customization/exceptions/) to configuring exceptions, my `dbt_project_evaluator_exceptions.csv` is:

```csv
fct_name,column_name,id_to_exclude,comment
fct_root_models,common_dim_date,common_%, Models called common_ can empty root models.
```

Also I have disabled the `dbt_project_evaluator_exceptions`:

<img width="624" alt="image" src="https://github.com/dbt-labs/dbt-project-evaluator/assets/24504549/6cd11a9e-70f0-4dfa-af3c-467b7b11f67e">

when I use the command: 

```shell
dbt build --select package:dbt_project_evaluator dbt_project_evaluator_exceptions
```
I got error:

```log
03:23:20  Running with dbt=1.6.1
03:23:20  Registered adapter: redshift=1.6.1
03:23:20  Unable to do partial parsing because saved manifest not found. Starting full parse.

### List of issues raised by dbt_project_evaluator ###


03:23:23  [WARNING]: Found patch for macro "redefine_ref_and_source" which was not found
03:23:24  Encountered an error:
Compilation Error
  Model 'model.dbt_project_evaluator.fct_undocumented_models' (models/marts/documentation/fct_undocumented_models.sql) depends on a node named 'dbt_project_evaluator_exceptions' in package or project 'dbt_project_evaluator' which is disabled
```

How can I avoid this?

**Comment by b-per** [comment]
That's odd. Could you please share the content of `redefine_ref_and_source`?

I am wondering if there is a logic in there that is triggering this behaviour.

**Comment by b-per** [comment]
Hi @GavinChowUp , I was able to replicate the issue locally. This seems to be a bug with `dbt-unit-testing` and the update of the `ref()` command.

I'd recommend raising this in their repo.

I'll close this one as there is nothing we can do on this side but feel free to link this issue in the other repo so we can track it if you find a solution.
