### ISSUE TITLE
dbt_project_evaluator disagrees with dbt's own best practices guide for base models

### ISSUE THREAD

**Issue by patspam** [dbt-labs/dbt-project-evaluator#387]
I ran into a disagreement between `dbt_project_evaluator` and dbt's own [How we structure our dbt projects](https://docs.getdbt.com/guides/best-practices/how-we-structure/1-guide-overview) guide.

The guide includes two staging `base` models, inside the `models/staging/jaffle_shop/base` directory:

<img width="957" alt="image" src="https://github.com/dbt-labs/dbt-project-evaluator/assets/23515/84430b28-ebe6-4de5-8f8d-77e8e5ccb534">

These models are named:
- `base_jaffle_shop__customers.sql`
- `base_jaffle_shop__deleted_customers.sql`

If you try this in your own project, `dbt_project_evaluator` will complain that these models should have a `stg_` prefix.

And similarly, `fct_staging_dependent_on_staging` would fail, claiming that `staging` models are depending on other `staging` models.

Given that both of these recommendations come from dbt... can we get some consistency?

**Comment by ttusing** [comment]
I think adding `base` to the list of accepted "other prefixes" by default seems like a straightforward way to handle this gracefully.
