### ISSUE TITLE
stg_nodes failure

### ISSUE THREAD

**Issue by Frydafly** [dbt-labs/dbt-project-evaluator#390]
### Steps to reproduce

run `dbt build --select package:dbt_project_evaluator`

all models pass except for stg_nodes

### Expected results

stg_nodes builds 

### Screenshots and log output

```
19:28:27  Postgres adapter: Postgres error: value too long for type character varying(600)
19:28:27  On model.dbt_project_evaluator.stg_nodes: ROLLBACK
19:28:27  Timing info for model.dbt_project_evaluator.stg_nodes (execute): 2023-10-27 19:28:19.945495 => 2023-10-27 19:28:27.953701
19:28:27  On model.dbt_project_evaluator.stg_nodes: Close
19:28:27  Database Error in model stg_nodes (models/staging/graph/stg_nodes.sql)
  value too long for type character varying(600)
  compiled Code at target/run/dbt_project_evaluator/models/staging/graph/stg_nodes.sql
19:28:27  Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'ffbb0816-d823-4323-9373-8f279dff1642', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fdcc855dd30>]}
19:28:27  8 of 61 ERROR creating sql table model wfp_dbt_dev_1.stg_nodes ................. [ERROR in 8.04s]
19:28:27  Finished running node model.dbt_project_evaluator.stg_nodes
```

### System information
**The contents of your `packages.yml` file:**

```
---
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
  - package: dbt-labs/audit_helper
    version: 0.7.0
  - package: dbt-labs/codegen
    version: 0.9.0
  - package: dbt-labs/metrics
    version: 1.4.1
  - package: calogica/dbt_expectations
    version: 0.10.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.6.2

```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.4
```

### Are you interested in contributing the fix?

Sure

**Comment by Frydafly** [comment]
the content of the nodes seem to hit the varchar(600) limit-- I wonder if just increasing that (which is in the cross_db_shim macros, would allow this to run?

**Comment by b-per** [comment]
Can you try adding a file under your `macros` folder setting up a higher value?

For example, like:
```
{%- macro redshift__type_string() -%}
  {{ "VARCHAR(5000)" }}
{%- endmacro %}
```

I'd also be interested in knowing what column would be more than 600 chars.

**Comment by ReynaldoMR3** [comment]
Hello, I had the same issue and @b-per solution of increasing the size of the varchar in a new file: `macros/cross_db_shim/redshift_shims.sql.sql` and removing the `dispatch` from `dbt_project.yml` I was able to run the `stg_nodes`

**Comment by Frydafly** [comment]
thanks yes, worked for me too!

**Comment by b-per** [comment]
Thanks for the update!
