### ISSUE TITLE
Test output failed models

### ISSUE THREAD

**Issue by lp-stenn** [dbt-labs/dbt-project-evaluator#392]
### Describe the feature
When one of the tests within the package, fails, within the error message, I would like to see which models have in fact failed. 

### Describe alternatives you've considered

I could create a python script that runs these locally instead and output the dataframe into the terminal,

### Additional context
Is this feature database-specific? Which database(s) is/are relevant? Please include any other relevant context here.

this should apply to ALL databases that the project is ran against

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

This will help speed up and enable development, as developers can see failures as they run the test, rather than go back and forth between snowflake and the terminal to see test failures

**Comment by b-per** [comment]
Would [this example](https://dbt-labs.github.io/dbt-project-evaluator/0.8/customization/issues-in-log/) on how to print exceptions in the logs work for you?

**Comment by lp-stenn** [comment]
> Would [this example](https://dbt-labs.github.io/dbt-project-evaluator/0.8/customization/issues-in-log/) on how to print exceptions in the logs work for you?

actually this might be what we need

**Comment by dave-connors-3** [comment]
@lp-stenn closing this since it seems like Benoit's suggestion was what you were looking for! lemme know if we need to reopen
