### ISSUE TITLE
databricks: print_dbt_project_evaluator_issues - quoting

### ISSUE THREAD

**Issue by bram-83** [dbt-labs/dbt-project-evaluator#399]
### Describe the bug
Printing the results does not work when the databricks schema contains special characters 

### Steps to reproduce
using special characters in your schema: for example `ch-123`

### Expected results
the expected behaviour = printing the results

### Actual results
on-run-end failed, error:
 
[INVALID_IDENTIFIER] The identifier ch-51278 is invalid. Please, consider quoting it with back-quotes as `ch-51278`.(line 4, pos 28)
== SQL ==
/* {"app": "dbt", "dbt_version": "1.7.3", "dbt_databricks_version": "1.7.2", "databricks_sql_connector_version": "2.9.3", "profile_name": "user", "target_name": "qas", "connection_name": "master"} */
    
        select * from qas.ch-51278.fct_test_coverage
----------------------------^^^

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/dbt_external_tables
    version: 0.8.7
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]
  - package: dbt-labs/dbt_project_evaluator
    version: 0.8.0

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ x] other (specify: databricks)

**The output of `dbt --version`:**
Running with dbt=1.7.3
Registered adapter: databricks=1.7.2

### Additional context
dbt_project_evaluator > macros > on-run-end > print_dbt_project_evaluator_issues
set db_schema: quote a lowercase the three level namespace

**Comment by b-per** [comment]
When we do a new release you will be able to use ``print_dbt_project_evaluator_issues(quote='`')``
