### ISSUE TITLE
sql syntax is unconventional and fails when I install the package and run it.

### ISSUE THREAD

**Issue by dbrtly** [dbt-labs/dbt-project-evaluator#405]
### Describe the bug
The query is weird. When I add this package to my dbt project and run it, this model fails.
Suggest refactoring to conventionalize the query by moving the placeholders to the cte and selecting * from the cte.
On my testing, this change makes the error go away.
 
```sql
/* Bigquery won't let us `where` without `from` so we use this workaround */
with dummy_cte as (
    select 1 as foo
)

select 

    cast(null as {{ dbt.type_string() }} ) as unique_id,
    cast(null as {{ dbt.type_string() }} ) as name,
    cast(null as {{ dbt.type_string() }} ) as resource_type,
    cast(null as {{ dbt.type_string() }} ) as file_path,
    cast(True as boolean) as is_described,
    cast(null as {{ dbt.type_string() }} ) as exposure_type,
    cast(null as {{ dbt.type_string() }} ) as maturity,
    cast(null as {{ dbt.type_string() }} ) as package_name,
    cast(null as {{ dbt.type_string() }} ) as url,
    cast(null as {{ dbt.type_string() }} ) as owner_name,
    cast(null as {{ dbt.type_string() }} ) as owner_email,
    cast(null as {{ dbt.type_string() }} ) as meta

from dummy_cte
where false 
```

### Steps to reproduce
run the package on bigquery

### Expected results
pass all

### Actual results
```4 of 71 OK created sql table model main.stg_exposures ........................ [FAIL in 0.04s]```

### System information
unchanged from main

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [X] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: __duckdb_______)

**The output of `dbt --version`:**
```
➜  dbt-project-evaluator git:(refactor-simplify-cte) ✗ dbt --version                        
Core:
  - installed: 1.7.4
  - latest:    1.7.4 - Up to date!

Plugins:
  - bigquery: 1.7.2 - Up to date!
  - duckdb:   1.7.0 - Up to date!
```

### Additional context

proposed change to 
models/staging/graph/stg_exposures.sql

```sql
with
cte as (
    select
        cast(null as {{ dbt.type_string() }} ) as unique_id,
        cast(null as {{ dbt.type_string() }} ) as name,
        cast(null as {{ dbt.type_string() }} ) as resource_type,
        cast(null as {{ dbt.type_string() }} ) as file_path,
        cast(True as boolean) as is_described,
        cast(null as {{ dbt.type_string() }} ) as exposure_type,
        cast(null as {{ dbt.type_string() }} ) as maturity,
        cast(null as {{ dbt.type_string() }} ) as package_name,
        cast(null as {{ dbt.type_string() }} ) as url,
        cast(null as {{ dbt.type_string() }} ) as owner_name,
        cast(null as {{ dbt.type_string() }} ) as owner_email,
        cast(null as {{ dbt.type_string() }} ) as meta
)

select *
from cte
where false

```

### Are you interested in contributing the fix?
yes. https://github.com/dbrtly/dbt-project-evaluator/tree/refactor-simplify-cte

**Comment by dbrtly** [comment]
Also I tried overriding the model (and insert_resources_from_graph) in my project but now I get a ZeroDivisionError in file "<template>".

**Comment by b-per** [comment]
Hi. Could you please share the details of the SQL error on the BQ side?

Yes, the model is very unconventional but this is because we use some very unconventional ways to load the graph as well 😄

**Comment by daniel-bartley** [comment]
<blows raspberry>
I'm trying to minimally introduce the package to our project.

```dbt build --select project:dbt_project_evaluator ```

On the weekend and yesterday above command failed on stg_exposures (only that model). 
If I copy/pasting the query to the bigquery console it ran succesdfully.
I edited the file directly in the dbt_project_evaluator project and the dbt command succeeded. 

Today the job in the package works as is.
🤷

```
seeds:
  dbt_project_evaluator:
    +dataset: best_practices
models:
  dbt_project_evaluator:
    +dataset: best_practices
    +enabled: false
    staging:
      +enabled: true
    marts:
      core:
        +enabled: true
      dag:
        fct_duplicate_sources:
          +enabled: true
        fct_hard_coded_references:
          +enabled: true
      tests:
        +enabled: true

```

**Comment by daniel-bartley** [comment]
Does stg_exposures ever actually hydrated with data? How?

https://github.com/search?q=repo%3Adbt-labs%2Fdbt-project-evaluator%20stg_exposures&type=code

---

Why is there extra yml configuration in these unit tests compared to the models directory of the main project?

https://github.com/dbt-labs/dbt-project-evaluator/blob/821c013bec8f698d0f7d1720b5d00fd14e5415f7/integration_tests/models/dbt_project_evaluator_schema_tests/graph.yml#L12

**Comment by b-per** [comment]
Yes, those models are ingesting data in an unconventional way. We iterated quite a bit around this to solve different performance issues etc...

Today, those staging tables are hydrated/loaded via the `post_hook` in the config

```
{{
    config(
        materialized='table',
        post_hook="{{ insert_resources_from_graph(this, resource_type='exposures') }}"
    )
}}
```

What this `post_hook` does is that it generates the data in Jinja, and then loops through it doing a few `insert into` statements. And for the post hook to work we create this weird empty table at first.

One of the disadvantage of this approach is that the compiled/run code doesn't show the SQL run as part of the hook (which is likely to be what fails in your use case)

Could you either:

- look at the debug logs for the post_hook query and share it or find the statement that fails there
- or share with us your exposure config so we could try to replicate the issue?

By experience it might be related to some fields that have single quotes in them, and in that case we'd need to update the code to escape those single quotes.

**Comment by b-per** [comment]
Especially, can you check if there is a `'` in one of the exposures owner name?

**Comment by daniel-bartley** [comment]
No single quotes inside the string but we do have values like these patterns:
```
---
  owner:
    name: 'Fred Flintstone'
    email: 'fred@rocksinthehead.com' 
---
  owner:
    name: Peter Parker
    email: ''
---
  owner:
    name: "Fred Flintstone"
    email: ''fred@rocksinthehead.com"    
---
  owner:
    name: "Fred Flintstone"
    email: "" 
    
---
  owner:
    name: "Fred Flintstone"
    email: "" 
    
```

**Comment by b-per** [comment]
Is this one as-is in your project? `email: ''fred@rocksinthehead.com"`

There is a mix of single and double quotes here which might raise the issue.

I have pushed some changes to the package to the branch `fix/exposure-owner-name`. You could try to install the package via git (instead of the Hub) and point it to the new branch to see if this fixes the error.

If it does, we can get it merged soon.

**Comment by daniel-bartley** [comment]
sorry it's taken me so long to get back to you. I can't find the branch

**Comment by b-per** [comment]
Thanks, let's assume that the fix we did was good and we can open another issue if it is not the case
