### ISSUE TITLE
Comments are incorrectly flagged as hard coded references

### ISSUE THREAD

**Issue by deanmorin** [dbt-labs/dbt-project-evaluator#409]
### Describe the bug

In some cases comments get flagged as hard coded references.

### Steps to reproduce

In a comment, if a quoted string follows `from` or `join` it will be flagged as a hard coded reference.

```sql
-- from "a comment"
-- join "another comment"
-- from my_model
select
  1
from 
  {{ ref('my_model') }}
```

The first two comment lines (with the quoted strings) get flagged, the third line does not.

### Expected results

No hard coded references found.

### Actual results

Both `"a comment"` and `"another comment"` get flagged as hard coded references. 

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.3
  - latest:    1.7.4 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.7.1 - Up to date!
```

### Are you interested in contributing the fix?

Unfortunately I do not have time.

**Comment by dave-connors-3** [comment]
hey @deanmorin ! thanks for opening -- we can see if there's a straightforward way to skip commented lines. Can you help me understand why you might have `from` or `join` comments in your models?

**Comment by deanmorin** [comment]
@dave-connors-3 The actual comment that triggered this bug was describing what a particular CTE is for:

```sql
-- Find when the case first moves from "New" to any other status
```

**Comment by graciegoheen** [comment]
We currently use commented out SQL for our integration tests for hard-coded references, so if we were to make this change we'd need to rethink our tests for this package.

**Comment by b-per** [comment]
This has been fixed recently
See [here](https://github.com/dbt-labs/dbt-project-evaluator/blob/9f9c1db78e0382abb75a688a07a9196bf5fb171e/macros/find_all_hard_coded_references.sql#L19-L20).
