### ISSUE TITLE
Compatibility alias 'dataset' and ''project'

### ISSUE THREAD

**Issue by dbrtly** [dbt-labs/dbt-project-evaluator#423]
### Describe the bug
Missing fully compatibility with:
- 'dataset' as alias for schema
- 'project' as alias for database

For bigquery

### Steps to reproduce
Use the alias above for sources. 
Run dbt compile
dbt build --select package:dbt_project_evaluator

### Expected results
Should complete ok

### Actual results
Parsing Error
  Invalid sources config given in models\foo.yml @ sources .....
Ar path[]: Additional properties are no allowed('project' was unexpected. 

### System information
V0.9.0

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [X] other (specify: _duckdb_______)

**The output of `dbt --version`:**
```
core:
 - installed: 1.7.7
 - latest:    1.7.7

plugins:
 - duckdb: 1.7.1
```

### Are you interested in contributing the fix?
Yes

**Comment by dave-connors-3** [comment]
hey @dbrtly -- are you seeing a dbt-core compilation error when you're trying to use `project` and `dataset` in your source yml file? if so, this may be an issue for dbt-core rather than this package!
