### ISSUE TITLE
rejoining_of_upstream_concepts test doesn't ignore exposures and metrics correctly

### ISSUE THREAD

**Issue by AlexPuletti** [dbt-labs/dbt-project-evaluator#433]
### Describe the bug

It appears fct_rejoining_of_upstream_concepts is trying to filter out exposures and metrics [here ](https://github.com/dbt-labs/dbt-project-evaluator/blob/20aafc565c7c4db720c2c0433b45c6056f3619d1/models/marts/dag/fct_rejoining_of_upstream_concepts.sql#L5) but it's filtering using `('exposures', 'metrics')` when it looks like parent_resource_type and child_resource_type are actually **exposure** and **metric** (non-plural). Because of this, the filter isn't working properly.

### Steps to reproduce

We have an exposure in our dbt project and it's failing the rejoining_of_upstream_concepts check and I can see the resource_type is listed as 'exposure' not 'exposure**s**'
<img width="957" alt="Screen Shot 2024-02-27 at 9 41 14 PM" src="https://github.com/dbt-labs/dbt-project-evaluator/assets/84871222/f7b6c184-8577-41c2-b983-6490706fba83">

### Expected results

Exposures and Metrics successfully ignored by the rejoining_of_upstream_concepts test.

### Actual results

Exposures and Metrics are not successfully ignored by the rejoining_of_upstream_concepts test.

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/dbt_utils
    version: 1.0.0
    
  - package: calogica/dbt_expectations
    version: [">=0.8.0", "<0.9.0"]
  
  - package: dbt-labs/dbt_project_evaluator
    version: 0.5.0

  - package: mjirv/dbt_datamocktool
    version: 0.3.5

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [x] other (specify: **databricks**)

**The output of `dbt --version`:**
```
1.6
```

### Are you interested in contributing the fix?

Sure

**Comment by dave-connors-3** [comment]
hey @AlexPuletti! would welcome a PR if you're still interested!

**Comment by AlexPuletti** [comment]
happy to!
