### ISSUE TITLE
Feature - Automatic Fix Functionality for Fixable Violations

### ISSUE THREAD

**Issue by glevineLeap** [dbt-labs/dbt-project-evaluator#436]
### Describe the feature
Functionality to apply automatic fixes where possible in the style of `sqlfluff fix` or `rubocop --autocorrect`.

For example, [Hard Coded References](https://dbt-labs.github.io/dbt-project-evaluator/latest/rules/modeling/#hard-coded-references) violations could be automatically resolved by querying the DAG for a relevant reference and replacing the hardcoded table name.

### Describe alternatives you've considered
Implementing recommendations by hand.

### Additional context
- Rubocop implementation: https://docs.rubocop.org/rubocop/1.60/usage/autocorrect.html
- Sqlfluff implementation: https://docs.sqlfluff.com/en/stable/cli.html#sqlfluff-fix

### Who will this benefit?
Depending on the nature of the violations, this could expedite the process of having an existing dbt project conform to best practices. I'd like to implement a CI check but our project currently has 461 outstanding violations after running the evaluator for the first time, many of which I suspect are automatically fixable. If I could automatically resolve 50% of those, it would allow me to focus on more substantive project changes and get closer to implementing a CI check.

### Are you interested in contributing this feature?
No

**Comment by b-per** [comment]
Hi! Thanks for opening the issue.

This package being a dbt package, we can't edit files. So the idea is interesting but won't be achievable with dbt_project_evaluator.

If you want to get your code automatically fixed you could check at third party libraries like SQLFluff that you already listed or [dbt-checkpoint](https://github.com/dbt-checkpoint/dbt-checkpoint/tree/main)
