### ISSUE TITLE
Unused models

### ISSUE THREAD

**Issue by timhiebenthal** [dbt-labs/dbt-project-evaluator#462]
### Describe the feature
The evaluator currently spots unused sources.
Wouldn't it  make also sense to spot unused models, too like here: https://hub.getdbt.com/rjh336/dbt_model_usage/latest/

### Describe alternatives you've considered
This dbt package https://hub.getdbt.com/rjh336/dbt_model_usage/latest/ is already out there and works, but why to install two things for essentially the same thing

### Who will this benefit?
This helps governing large projects and reduce unnecessary clutter

**Comment by timhiebenthal** [comment]
Ok fair, then let's ignore the package of model_usage which indeed uses the Information-Schema to check if a model is QUERIED.
Probably you indeed need to exclude the dim/fact/reporting-layer, but I would consider it part of the scope of the project evaluator to tell me if there are models which aren't REFERENCED anywhere, right?

I'm on vacation the next few weeks, but would be also in to draft a potential solution in a PR

**Comment by cedric-orange** [comment]
In my case, all public models are configured in one or more exposure.
This exposure described in which case models are used and allow us to contact our users when a data quality issue or freshness problem occurs.
