### ISSUE TITLE
Bug in Overriding primary_key_test_macros Variable

### ISSUE THREAD

**Issue by savannahchunn** [dbt-labs/dbt-project-evaluator#470]
### Describe the bug
Overriding the primary_key_test_macros variable to a set of tests that does not include a reference to the dbt.test_unique causes an unresolved column error in the int_model_test_summary model.

### Steps to reproduce
At first, I set the primary_key_test_macros variable to be just the below boxed section of our team's custom unique test and the built-in dbt not null test.
![image](https://github.com/dbt-labs/dbt-project-evaluator/assets/123206442/888ac9b7-d1fc-4e26-b551-4ad5cb0bb45b)

### Expected results
I expected these two tests to be an acceptable set for the primary key check.

### Actual results
The use of just the boxed test macros resulted in the below column error where int_mdoel_test_summary was looking for a is_test_unique column in the all_graph_resources model, but due to my team's custom unique test, only a is_test_unique_full column was created in all_graph_resources.
![image](https://github.com/dbt-labs/dbt-project-evaluator/assets/123206442/bbba9b23-6129-45b8-9f07-6c21b7475857)

### Screenshots and log output
Screenshots seen above.

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: calogica/dbt_date
    version: 0.10.1
  - package: dbt-labs/dbt_utils
    version: 1.2.0
  - package: dbt-labs/dbt_project_evaluator
    version: 0.12.0

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [X] other (specify: Databricks)

**The output of `dbt --version`:**
![image](https://github.com/dbt-labs/dbt-project-evaluator/assets/123206442/58312d67-d71c-46e6-8d1e-304b9779b6d4)

### Additional context
I think the below line 18 of int_model_test_summary is causing the issue, but I'm not sure if this is_test_unqiue setup is needed by other project evaluator processes.
![image](https://github.com/dbt-labs/dbt-project-evaluator/assets/123206442/3bb3c548-4c11-43cf-871a-43ddf815f9ac)

Instead of trying to change the project evaluator code, I took a band-aid approach by updating our primary_key_test_macros variable to include a second set of tests, the dbt_utils.test_unqiue_combination_of_columns and the dbt.test_unqiue macros. Having the dbt unqiue test resolves the unknown column error I was getting, but it does open up the slim chance that models in our project pass the evaluator check with a testing approach different than our team's standard.
![image](https://github.com/dbt-labs/dbt-project-evaluator/assets/123206442/d970014f-13e4-46b2-a4de-42dcbc0547b1)

### Are you interested in contributing the fix?
Not at this time, but I'm happy to provide more context if needed.

**Comment by b-per** [comment]
Thanks for the report. I will have a look at it today.
