### ISSUE TITLE
Option to exclude types of materializations from documentation rules

### ISSUE THREAD

**Issue by evanodell** [dbt-labs/dbt-project-evaluator#481]
### Describe the feature

The documentation rules, such as `fct_undocumented_models`, apply to all models including ephemeral models. As ephemeral models are used for lightweight transformation or selections, typically directly from source tables, their documentation is less of a priority than other materialization types. 

Would create a project level var than can be referenced in `fct_undocumented_models`, e.g.

```
final as (

    select
        resource_name,
        model_type

    from all_resources
    where not is_described and resource_type = 'model' and not materialized = '{{ var("excluded_materialization") }}'

)
```

### Describe alternatives you've considered

Either switching off `fct_undocumented_models` or going through all the ephemeral models and adding documentation by hand. 

### Additional context

Unsure if there are other rules it may be sensible to add an option to exclude ephemeral models from. 

### Who will this benefit?

Users with significant numbers of undocumented ephemeral tables, but otherwise good documentation coverage.

### Are you interested in contributing this feature?

Yes, I can contribute if there is community interest in this feature. Would allow any type of materialization to be specified for exclusion.

**Comment by b-per** [comment]
Hi @evanodell . Thanks for raising this issue. I had a chat with the team but we're not convinced that excluding ephemeral models would fit every use case. Some people might want to make sure that they are documented as well.

As it seems that it might quite specific to your situtation I would recommend:
1. deactivating the `fct_undocumented_models` model in the project evaluator package
2. creating your own version of `fct_undocumented_models` (or with an other name), as a slight change from the OOTB version.
