### ISSUE TITLE
Compilation Error in model stg_sources: 'None' has no attribute 'warn_after'

### ISSUE THREAD

**Issue by shah204** [dbt-labs/dbt-project-evaluator#482]
### Describe the bug
I am attempting to install the package and run `dbt build --select package:dbt_project_evaluator`. When I do this, I get the following error message:

```
Compilation Error in model stg_sources (models/staging/graph/stg_sources.sql)
  'None' has no attribute 'warn_after'
  
  > in macro get_resource_values (macros/unpack/get_resource_values.sql)
  > called by macro insert_resources_from_graph (macros/insert_resources_from_graph.sql)
  > called by macro run_hooks (macros/materializations/hooks.sql)
  > called by macro materialization_table_redshift (macros/materializations/table.sql)
  > called by model stg_sources (models/staging/graph/stg_sources.sql)
```

### Steps to reproduce
I am on dbt version 1.8.0, and dbt_project_evaluator version 0.13.0.

### Expected results
Run all models.

### Actual results
Errors on stg_sources.

### System information
**The contents of your `packages.yml` file:**
<img width="552" alt="Screenshot 2024-08-20 at 10 34 50 AM" src="https://github.com/user-attachments/assets/cefc6ec6-b8b5-4335-8ac7-e87439a068fa">

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] trino/starburst
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.8.0
```

**Comment by b-per** [comment]
Do you have `freshness: null` somewhere in the YML of your sources? It seems to be the cause of the issue but I don't see it in the packages that you are installing.

**Comment by shah204** [comment]
Hey @b-per, thanks for the quick response. Going to a lower version did resolve this for now 😄
 
 I have the following in my sources.yml for one source schema:
 
```
     freshness:
      warn_after: {count: 24, period: hour}
```

**Comment by b-per** [comment]
I was able to repro it. I have a PR out and will release a new patch version of the provider when I get approval

**Comment by b-per** [comment]
0.13.1 should be available on the dbt Hub in the next couple of hours

**Comment by shah204** [comment]
Thank you!
