### ISSUE TITLE
Warn when a dbt project contains `tests:` instead of `data_tests:`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-project-evaluator#489]
### Describe the feature

Raise a warning whenever the `tests:` config is used instead of `data_tests:` (in order to disambiguate from `unit_tests:`).

This scenario is going to be removed as a deprecation warning in dbt-core when https://github.com/dbt-labs/dbt-core/issues/10564 is resolved.

But `data_tests:` is the recommended best practice (even if `tests:` is supported indefinitely by dbt-core).

### Describe alternatives you've considered

1. Keeping it as as deprecation warning in dbt-core.
1. Converting to just an info level or debug level message in the dbt-core logs.
1. Create some new dbt package that handles things like this, [#477](https://github.com/dbt-labs/dbt-project-evaluator/issues/477), etc. 

### Additional context

`data_tests:` was added in v1.8, so any versions of dbt-core earlier than that can't use it.

This is similar in spirit to https://github.com/dbt-labs/dbt-project-evaluator/issues/477.

### Who will this benefit?

Users that want to be aware of best practices that aren't official warnings in dbt-core.

**Comment by dave-connors-3** [comment]
given that we are removing this warning and do not plan to remove back compatibility, we are going to close this for now!
