### ISSUE TITLE
sqlserver adapter support

### ISSUE THREAD

**Issue by danielkroeders** [dbt-labs/dbt-project-evaluator#522]
### Describe the feature
It would be very nice if this package would also support the dbt-sqlserver adapter.

### Additional context
SQL Server

### Who will this benefit?
Would be usefull for everybody that uses the SQL Server adapter.

**Comment by b-per** [comment]
Hi. Yes, we'd like this too. It is already tracked in https://github.com/dbt-labs/dbt-project-evaluator/issues/229
