### ISSUE TITLE
Expand structure coverage 

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-project-evaluator#61]
@dave-connors-3 Other ideas include:
- models without appropriate pre-fix (though maybe that's in a separate naming conventions category)
- insuring each model type is in the appropriate folder (intermediate models are nested in intermediate folder, marts in marts, etc.)
- models are tested and documented in a <dir_name>.yml file in the same directory as the models (not sure yet how to do the documentation piece of this)
- any extra documentation in a docs block is placed in a <dir_name>.md file in the same directory (note: do we have doc blocks as resources yet? do we want them?)

Would be curious if other people have thoughts here! Was mostly looking at [this](https://discourse.getdbt.com/t/how-we-structure-our-dbt-projects/355) article.

_Originally posted by @graciegoheen in https://github.com/dbt-labs/dbt_project_evaluator/issues/55#issuecomment-1077925101_

**Comment by wasilaq** [comment]
> models are tested and documented in a <dir_name>.yml file in the same directory as the models (not sure yet how to do the documentation piece of this)

As noted, info on documentation doesn't currently exist in the graph object so this issue will be closed out by PR #103
