### ISSUE TITLE
should this package be disabled by default?

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#66]
per @b-per 's question on #65 , should we treat this package as disabled by default, and allow end users to opt in to this package executing?

This gets to a larger question about usage and deployment of this package, which is a really good question! per [Sean in the slack](https://dbt-labs.slack.com/archives/C01JNSRKTC3/p1648055931735499) thread, it sounds like there would likely be appetite to have this run as a CI check.

**Comment by graciegoheen** [comment]
@dave-connors-3 Can we close this? I added instructions for how to use this package as a CI check

**Comment by dave-connors-3** [comment]
@graciegoheen oh big time

what a relic
