### ISSUE TITLE
exclusion criteria investigation

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-project-evaluator#89]
Why are we only excluding _models_ from the `dbt_project_evaluator` package? Shouldn't we exclude _everything_ in the package?

_Originally posted by @graciegoheen in https://github.com/dbt-labs/dbt-project-evaluator/pull/85#discussion_r859021318_

**Comment by graciegoheen** [comment]
A related question came up when the internal analytics team was testing this out, "will documentation coverage also catch models from packages that aren't documented?"

**Comment by b-per** [comment]
Kind of related to #135 As well
